version: "2"
run:
  go: "1.22"
linters:
  default: none
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gomodguard
    - govet
    - importas
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - tagliatelle
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 200
    gocyclo:
      min-complexity: 20
    gomodguard:
      allowed:
        modules:
          - github.com/nextmv-io/sdk
    lll:
      line-length: 120
    tagliatelle:
      case:
        rules:
          json: snake
        use-field-name: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
          - revive
        path: options\.go
      - linters:
          - goconst
          - gocyclo
        path: options_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
